# Generated by Django 4.2.3 on 2024-11-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STORE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(choices=[('Motherboard', 'Motherboard'), ('Processor', 'Processor'), ('Storage', 'Storage'), ('Memory', 'Memory')], default=('Motherboard', 'Motherboard'), max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_img', models.ImageField(upload_to='')),
                ('product_price', models.BigIntegerField()),
                ('product_quantity', models.BigIntegerField()),
                ('product_rate', models.BigIntegerField(default=0)),
                ('isSoldOut', models.BooleanField(default=False)),
                ('product_store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='STORE.store')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_context', models.TextField()),
                ('product_topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PRODUCT.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bundle_category', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop')], default=('Laptop', 'Laptop'), max_length=100)),
                ('bundle_name', models.CharField(max_length=200)),
                ('memory_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memory', to='PRODUCT.product')),
                ('motherboard_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_motherboard', to='PRODUCT.product')),
                ('processor_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_processor', to='PRODUCT.product')),
                ('storage_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_storage', to='PRODUCT.product')),
            ],
        ),
    ]
