# Generated by Django 4.2.3 on 2024-11-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Motherboard', 'Motherboard'), ('CPU', 'CPU'), ('Storage', 'Storage'), ('Memory', 'Memory'), ('Power Supply Unit', 'Power Supply Unit'), ('CPU Cooler', 'CPU Cooler'), ('Graphics Card', 'Graphics Card'), ('Case', 'Case')], default=('Motherboard', 'Motherboard'), max_length=200),
        ),
    ]
