# Generated by Django 4.2.3 on 2024-11-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0002_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='Desert.jpg', upload_to=''),
        ),
    ]
