# Generated by Django 4.2.3 on 2024-11-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0003_alter_product_product_img'),
        ('PRODUCT', '0003_laptop_rename_productbundle_packagebundle'),
    ]

    operations = [
    ]
