# Generated by Django 4.2.3 on 2024-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0004_merge_20241123_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='banner',
            field=models.ImageField(default='Hydrangeas.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='packagebundle',
            name='bundle_category',
            field=models.CharField(choices=[('Desktop', 'Desktop')], default=('Desktop', 'Desktop'), max_length=100),
        ),
    ]
