# Generated by Django 4.2.3 on 2024-11-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
        ('PRODUCT', '0006_packagebundle_cpu_cooler_unit_packagebundle_gpu_unit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Parts',
        ),
    ]
