# Generated by Django 4.2.3 on 2024-11-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0007_rename_product_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='product_category',
            new_name='parts_category',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_description',
            new_name='parts_description',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_id',
            new_name='parts_id',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_img',
            new_name='parts_img',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_name',
            new_name='parts_name',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_price',
            new_name='parts_price',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_quantity',
            new_name='parts_quantity',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_rate',
            new_name='parts_rate',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='product_store',
            new_name='parts_store',
        ),
    ]
