# Generated by Django 4.2.3 on 2024-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0008_rename_product_category_parts_parts_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebundle',
            name='bundle_category',
            field=models.CharField(choices=[('PreBuild', 'PreBuild'), ('UserBuild', 'UserBuild')], default=('PreBuild', 'PreBuild'), max_length=100),
        ),
    ]
