# Generated by Django 4.2.3 on 2024-11-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0009_alter_packagebundle_bundle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='power_supply',
        ),
    ]
