# Generated by Django 4.2.3 on 2024-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0010_remove_laptop_power_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='wifi',
            field=models.CharField(max_length=100),
        ),
    ]
