# Generated by Django 4.2.3 on 2024-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0011_alter_laptop_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.BigIntegerField(default=150),
        ),
    ]
