# Generated by Django 4.2.3 on 2024-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0012_laptop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebundle',
            name='bundle_total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
