# Generated by Django 5.1.3 on 2024-11-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PRODUCT", "0014_packagebundle_bundle_banner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packagebundle",
            old_name="bundle_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="packagebundle",
            old_name="bundle_total_price",
            new_name="price",
        ),
    ]
