# Generated by Django 4.2.3 on 2024-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_img', models.ImageField(upload_to='')),
                ('product_price', models.BigIntegerField()),
                ('product_quantity', models.BigIntegerField()),
            ],
        ),
    ]
