# Generated by Django 4.2.3 on 2024-11-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0002_product_product_issoldout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_isSoldOut',
            new_name='isSoldOut',
        ),
    ]
