# Generated by Django 4.2.3 on 2024-11-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0005_product_product_rate_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
