# Generated by Django 4.2.3 on 2024-11-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Pre-Build', 'Pre-Build')], default=('Laptop', 'Laptop'), max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
