# Generated by Django 4.2.3 on 2024-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0007_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Pre-Build', 'Pre-Build'), ('Motherboard', 'Motherboard'), ('Processor', 'Processor'), ('Storage', 'Storage'), ('Memory', 'Memory')], default=('Laptop', 'Laptop'), max_length=200),
        ),
    ]
