# Generated by Django 4.2.3 on 2024-11-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0008_alter_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=200)),
                ('memory_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memory', to='PRODUCT.product')),
                ('motherboard_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_motherboard', to='PRODUCT.product')),
                ('processor_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_processor', to='PRODUCT.product')),
                ('storage_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_storage', to='PRODUCT.product')),
            ],
        ),
    ]
