# Generated by Django 4.2.3 on 2024-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0010_remove_productbundle_id_productbundle_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Motherboard', 'Motherboard'), ('Processor', 'Processor'), ('Storage', 'Storage'), ('Memory', 'Memory')], default=('Laptop', 'Laptop'), max_length=200),
        ),
    ]
