# Generated by Django 4.2.3 on 2024-11-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0011_alter_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbundle',
            old_name='unit',
            new_name='bundle_name',
        ),
    ]
