# Generated by Django 4.2.3 on 2024-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0012_rename_unit_productbundle_bundle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbundle',
            name='unit_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
