# Generated by Django 4.2.3 on 2024-11-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
        ('PRODUCT', '0013_alter_productbundle_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='STORE.store'),
        ),
    ]
