# Generated by Django 4.2.3 on 2024-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_remove_basket_product_basketitem_basket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(null=True, to='USER.basketitem'),
        ),
    ]
