# Generated by Django 4.2.3 on 2024-11-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_alter_basket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(blank=True, to='USER.basketitem'),
        ),
    ]
