# Generated by Django 4.2.3 on 2024-11-24 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PRODUCT', '0014_packagebundle_bundle_banner'),
        ('USER', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('baskteItem_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='owner',
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWNER', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='basketitems',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BASKET_MAIN', to='USER.basket'),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='basket_laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LAPTOP_ITEMS', to='PRODUCT.laptop'),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='basket_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PACKAGE_ITEMS', to='PRODUCT.packagebundle'),
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ITEMS', to='USER.basketitems'),
        ),
    ]
