# Generated by Django 4.2.3 on 2024-11-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_basket_basket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ITEMS', to='USER.basketitems'),
        ),
    ]
