# Generated by Django 4.2.3 on 2024-11-24 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USER', '0008_alter_basket_basket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OWNER', to=settings.AUTH_USER_MODEL),
        ),
    ]
