# Generated by Django 4.2.3 on 2024-11-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0010_alter_basketitems_basket_laptop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
