# Generated by Django 4.2.3 on 2024-11-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0011_basket_basket_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='basket_total_price',
            new_name='basket_total',
        ),
    ]
