# Generated by Django 4.2.3 on 2024-11-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0014_packagebundle_bundle_banner'),
        ('USER', '0012_rename_basket_total_price_basket_basket_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_items',
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_laptop_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LAPTOP', to='PRODUCT.laptop'),
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_package_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PACKAGE', to='PRODUCT.packagebundle'),
        ),
        migrations.DeleteModel(
            name='BasketItems',
        ),
    ]
