# Generated by Django 4.2.3 on 2024-11-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0013_remove_basket_basket_items_basket_basket_laptop_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_total',
        ),
    ]
