# Generated by Django 4.2.3 on 2024-11-25 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0016_basketitems_remove_basket_basket_laptop_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_total_price',
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ITEMS', to='USER.basketitems'),
        ),
    ]
