# Generated by Django 5.1.3 on 2024-11-25 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PRODUCT", "0014_packagebundle_bundle_banner"),
        ("USER", "0017_remove_basket_basket_total_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="basket_owner",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="basket",
            name="basket_items",
        ),
        migrations.AlterField(
            model_name="basketitems",
            name="basket_laptop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="LAPTOP_ITEMS",
                to="PRODUCT.laptop",
            ),
        ),
        migrations.AlterField(
            model_name="basketitems",
            name="basket_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PACKAGE_ITEMS",
                to="PRODUCT.packagebundle",
            ),
        ),
    ]
