# Generated by Django 5.1.3 on 2024-11-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0018_rename_basket_owner_basket_user_id_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitems",
            name="basket_laptop",
        ),
        migrations.RemoveField(
            model_name="basketitems",
            name="basket_package",
        ),
        migrations.AddField(
            model_name="basketitems",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="basketitems",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
