# Generated by Django 5.1.3 on 2024-11-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0019_remove_basketitems_basket_laptop_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitems",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="basketitems",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
