# Generated by Django 5.1.3 on 2024-11-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PRODUCT", "0014_packagebundle_bundle_banner"),
        ("USER", "0020_alter_basketitems_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitems",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="basketitems",
            name="object_id",
        ),
        migrations.AddField(
            model_name="basketitems",
            name="basket_laptop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="LAPTOP_ITEMS",
                to="PRODUCT.laptop",
            ),
        ),
        migrations.AddField(
            model_name="basketitems",
            name="basket_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PACKAGE_ITEMS",
                to="PRODUCT.packagebundle",
            ),
        ),
    ]
