# Generated by Django 5.1.3 on 2024-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0021_remove_basketitems_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="basket_id",
        ),
        migrations.AddField(
            model_name="basket",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1000,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basket",
            name="product_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="basket",
            name="product_name",
            field=models.CharField(default="PRODUCT_NAME", max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basket",
            name="product_price",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="basket",
            name="user_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name="BasketItems",
        ),
    ]
