# Generated by Django 5.1.3 on 2024-11-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("USER", "0022_remove_basket_basket_id_basket_id_basket_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="product_id",
            new_name="basket_item_id",
        ),
        migrations.RenameField(
            model_name="basket",
            old_name="product_name",
            new_name="basket_item_name",
        ),
        migrations.RenameField(
            model_name="basket",
            old_name="product_price",
            new_name="basket_item_price",
        ),
    ]
